### ISSUE TITLE
Better to have use cases defined to perform these operations.

### ISSUE THREAD

**Issue by anmolvermamm** [kunalkalra97/download-manager#1]
https://github.com/kunalkalra97/download-manager/blob/8d0ebc824e7ec75ede04ec6658730e078e58db4f/DownloadManagerCore/src/main/java/com/kunalkalra/downloadmanagercore/fileIO/FileManager.kt#L14

For Ex:
FileCopyUseCase(InFile:File,outFile:File) : BaseUseCase(Dispatchers.IO)

**Comment by kunalkalra97** [comment]
Added Use cases for File IO and Network Operations
